[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "samos"
version = "0.1.0"
description = "SamOS Phase 4 scaffold"
authors = [{ name = "Mark B" }]
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "pytest",
    "pytest-cov",
    "flake8",
    "black"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["samos*"]
[tool.pytest.ini_options]
# Only collect tests in the tests/ directory
testpaths = ["tests"]
# Only treat files named test_*.py as tests
python_files = ["test_*.py"]
# Nice defaults for CI/local runs
addopts = "-q --maxfail=1 --disable-warnings"
