name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (project + dev tools)
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -e ".[dev]"
          # belt-and-braces to avoid 'command not found'
          python -m pip install ruff mypy

      - name: Show environment (debug)
        run: |
          python -V
          python -c "import sys; print(sys.executable)"
          python -m pip freeze | sed -n '1,120p'

      - name: Lint (ruff)
        run: python -m ruff check .

      - name: Type-check (mypy)
        run: python -m mypy .

      - name: Run tests
        run: python -m pytest -q --disable-warnings
