name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # set the floor you want; you can tighten this later
  COVERAGE_MIN: "0.50"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov flake8 black

      - name: Install package
        run: pip install -e .

      - name: Lint (flake8)
        run: flake8 .

      - name: Format check (black)
        run: black --check .

      - name: Run tests with coverage
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=samos --cov-branch \
            --cov-report=term-missing \
            --cov-report=xml:coverage.xml

      - name: Enforce coverage threshold
        run: |
          python - << 'PY'
          import os, sys, xml.etree.ElementTree as ET
          path = "coverage.xml"
          try:
              root = ET.parse(path).getroot()
          except Exception as e:
              print(f"ERROR: cannot read {path}: {e}")
              sys.exit(1)

          rate = float(root.attrib.get("line-rate", "0"))
          pct = rate * 100.0
          floor = float(os.environ.get("COVERAGE_MIN", "0.80")) * 100.0
          print(f"Total coverage: {pct:.2f}%  (required ≥ {floor:.2f}%)")
          if pct + 1e-9 < floor:
              print("Coverage too low – failing the build.")
              sys.exit(1)
          print("Coverage OK.")
          PY

      - name: Upload coverage.xml artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
