name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest pytest-cov flake8 black

      - name: Lint (flake8)
        run: flake8 .

      - name: Format check (black)
        run: black --check .

      - name: Run tests with coverage
        run: python -m pytest

      - name: Upload coverage.xml artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: error
